# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Boop Boop
email: angeladanwang@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Where I write about things that are relatively relevant
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://angelawang.co" # the base hostname & protocol for your site
github_username:  vaticancameo

# Build settings
markdown: kramdown
